apiVersion: v1
kind: Secret
metadata:
  name: playasset-app-secret
  namespace: playasset
type: Opaque
stringData:
  DB_USER: root
  DB_PASSWORD: change-me
  EXTERNAL_MARKET_API_KEY: ""
  EXTERNAL_NEWS_API_KEY: ""
