apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: playasset-public
  namespace: playasset
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:111111111111:certificate/REPLACE_ME
    alb.ingress.kubernetes.io/ssl-redirect: "443"
spec:
  rules:
    - host: app.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: playasset-server
                port:
                  number: 8080
          - path: /actuator
            pathType: Prefix
            backend:
              service:
                name: playasset-server
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: playasset-web
                port:
                  number: 80
    - host: kafka-ui.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: playasset-kafka-ui
                port:
                  number: 8080
